config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, controllers: {
    sessions: 'doctors/doctor_devise/sessions',
    passwords: 'doctors/doctor_devise/passwords',
    registrations: 'doctors/doctor_devise/registrations'
  }
  devise_for :patients, controllers: {
    sessions: 'patients/patient_devise/sessions',
    passwords: 'patients/patient_devise/passwords',
    registrations: 'patients/patient_devise/registrations'
  }
  namespace :doctors, path: 'doctor' do
    get 'dashboard', to: 'dashboard#index'
    resources :profile, only: %i[index update]
    resources :appointments, only: %i[index show] do
      member do
        get 'confirm'
        get 'reject'
      end
    end
  end

  namespace :patients, path: 'patient' do
    get 'dashboard', to: 'dashboard#index'
    resources :profile, only: %i[index update]
    resources :appointments
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validate :date, :time
  
  after_create :change_status

  def change_status
    update(status: 'Request')
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates :name, :phone, presence: true
   validates :phone, length: {maximum: 15}

   has_many :appointments, dependent: :destroy
end

app/controllers/doctors/appointments_controller.rb
module Doctors
  class AppointmentsController < ApplicationController
    before_action :authenticate_doctor!
    before_action :set_peginate, only: :index
    before_action :set_appointment, only: %i[show confirm reject]

    def index
      @appointments = current_doctor.appointments.page(@page).per(@per_page)
    end

    def confirm
      @appointment.update(status: 'Confirm')
      flash[:success] = "Appointment Confirmed"
      redirect_to doctors_appointments_path
    end

    def reject
      @appointment.update(status: 'Reject')
      flash[:success] = "Appointment Rejected"
      redirect_to doctors_appointments_path
    end

    def show
    end

    private

    def set_appointment
      @appointment = Appointment.find_by(id: params[:id])
      redirect_to doctors_appointments_path if @appointment.blank?
    end
  end
end

app/controllers/patients/appointments_controller.rb
module Patients
  class AppointmentsController < ApplicationController
    before_action :authenticate_patient!
    before_action :set_peginate, only: :index
    before_action :set_appointment, only: %i[show destroy edit update]

    def index
      @appointments = current_patient.appointments.page(@page).per(@per_page)
    end

    def new
      @appointment = current_patient.appointments.new
    end

    def show
    end

    def destroy
      @appointment.destroy
      flash[:success] = "Appointment Deleted"
      redirect_to patients_appointments_path
    end

    def edit
    end

    def create
      @appointment = current_patient.appointments.new(appointment_params)
      available, error = check_available_time
      if available
        if @appointment.save
          flash[:success] = "Appointment Created"
          redirect_to patients_appointment_path(@appointment.id)
        else
          flash[:notice] = @appointment.errors.full_messages.join(",")
          render :new
        end
      else
        flash[:notice] = error
        render :new
      end
    end

    def update
      available, error = check_available_time
      if available
        if @appointment.update(appointment_params)
          flash[:success] = "Appointment Updated"
          redirect_to patients_appointment_path(@appointment.id)
        else
          flash[:notice] = @appointment.errors.full_messages.join(",")
          render :edit
        end
      else
        flash[:notice] = error
        render :edit
      end
    end

    private

    def set_appointment
      @appointment = Appointment.find_by(id: params[:id])
      redirect_to patients_dashboard_path if @appointment.blank?
    end

    def appointment_params
      params.require(:appointment).permit(:doctor_id, :date, :time, :description)
    end

    def check_available_time
      date = params[:appointment][:date]
      time = params[:appointment][:time]
      doctor = Doctor.find_by(id: params[:appointment][:doctor_id])
      if doctor.present?
        unavailables = doctor.unavailables.where(date: date)
        if unavailables.present?
          unavailable_time = false
          unavailables.each do |u|
            if u.closing_time.strftime("%H:%M") > time && u.opening_time.strftime("%H:%M") < time
              unavailable_time = true
              break
            end
          end
          if unavailable_time == true
            check_regular_time(doctor, time)
          else
            return false, "Doctor not available in this time and date"
          end
        else
          check_regular_time(doctor, time)
        end
      else
        return false , "Please Select Doctor"
      end
    end

    def check_regular_time(doctor, time)
      available = doctor.operating_hour
      if available.opening_time.strftime("%H:%M") < time && available.closing_time.strftime("%H:%M") > time
        return true, "Doctor available"
      else
        return false , "Doctor Not available in this time"
      end
    end
  end
end

app/controllers/patients/dashboard_controller.rb
module Patients
  class DashboardController < ApplicationController
    before_action :authenticate_patient!

    def index
    end
  end
end

app/controllers/patients/patient_devise/confirmations_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class ConfirmationsController < Devise::ConfirmationsController
      # GET /resource/confirmation/new
      # def new
      #   super
      # end

      # POST /resource/confirmation
      # def create
      #   super
      # end

      # GET /resource/confirmation?confirmation_token=abcdef
      # def show
      #   super
      # end

      # protected

      # The path used after resending confirmation instructions.
      # def after_resending_confirmation_instructions_path_for(resource_name)
      #   super(resource_name)
      # end

      # The path used after confirmation.
      # def after_confirmation_path_for(resource_name, resource)
      #   super(resource_name, resource)
      # end
    end
  end
end

app/controllers/patients/patient_devise/omniauth_callbacks_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class OmniauthCallbacksController < Devise::OmniauthCallbacksController
      # You should configure your model like this:
      # devise :omniauthable, omniauth_providers: [:twitter]

      # You should also create an action method in this controller like this:
      # def twitter
      # end

      # More info at:
      # https://github.com/plataformatec/devise#omniauth

      # GET|POST /resource/auth/twitter
      # def passthru
      #   super
      # end

      # GET|POST /users/auth/twitter/callback
      # def failure
      #   super
      # end

      # protected

      # The path used when OmniAuth fails
      # def after_omniauth_failure_path_for(scope)
      #   super(scope)
      # end
    end
  end
end

app/controllers/patients/patient_devise/passwords_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class PasswordsController < Devise::PasswordsController
      # GET /resource/password/new
      # def new
      #   super
      # end

      # POST /resource/password
      # def create
      #   super
      # end

      # GET /resource/password/edit?reset_password_token=abcdef
      # def edit
      #   super
      # end

      # PUT /resource/password
      # def update
      #   super
      # end

      # protected

      # def after_resetting_password_path_for(resource)
      #   super(resource)
      # end

      # The path used after sending reset password instructions
      # def after_sending_reset_password_instructions_path_for(resource_name)
      #   super(resource_name)
      # end
    end
  end
end

app/controllers/patients/patient_devise/registrations_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class RegistrationsController < Devise::RegistrationsController
      # before_action :configure_sign_up_params, only: [:create]
      # before_action :configure_account_update_params, only: [:update]

      # GET /resource/sign_up
      # def new
      #   super
      # end

      # POST /resource
      # def create
      #   super
      # end

      # GET /resource/edit
      # def edit
      #   super
      # end

      # PUT /resource
      # def update
      #   super
      # end

      # DELETE /resource
      # def destroy
      #   super
      # end

      # GET /resource/cancel
      # Forces the session data which is usually expired after sign
      # in to be expired now. This is useful if the user wants to
      # cancel oauth signing in/up in the middle of the process,
      # removing all OAuth session data.
      # def cancel
      #   super
      # end

      # protected

      # If you have extra params to permit, append them to the sanitizer.
      # def configure_sign_up_params
      #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
      # end

      # If you have extra params to permit, append them to the sanitizer.
      # def configure_account_update_params
      #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
      # end

      # The path used after sign up.
      # def after_sign_up_path_for(resource)
      #   super(resource)
      # end

      # The path used after sign up for inactive accounts.
      # def after_inactive_sign_up_path_for(resource)
      #   super(resource)
      # end
    end
  end
end

app/controllers/patients/patient_devise/sessions_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class SessionsController < Devise::SessionsController
      # before_action :configure_sign_in_params, only: [:create]

      # GET /resource/sign_in
      # def new
      #   super
      # end

      # POST /resource/sign_in
      # def create
      #   super
      # end

      # DELETE /resource/sign_out
      # def destroy
      #   super
      # end

      # protected

      # If you have extra params to permit, append them to the sanitizer.
      # def configure_sign_in_params
      #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
      # end
    end
  end
end

app/controllers/patients/patient_devise/unlocks_controller.rb
# frozen_string_literal: true
module Patients
  module PatientDevise
    class UnlocksController < Devise::UnlocksController
      # GET /resource/unlock/new
      # def new
      #   super
      # end

      # POST /resource/unlock
      # def create
      #   super
      # end

      # GET /resource/unlock?unlock_token=abcdef
      # def show
      #   super
      # end

      # protected

      # The path used after sending unlock password instructions
      # def after_sending_unlock_instructions_path_for(resource)
      #   super(resource)
      # end

      # The path used after unlocking the resource
      # def after_unlock_path_for(resource)
      #   super(resource)
      # end
    end
  end
end

app/controllers/patients/profile_controller.rb
module Patients
  class ProfileController < ApplicationController
    before_action :authenticate_patient!
    before_action :set_patient, only: %i[update index]

    def index
    end

    def update
      if @patient.update(patient_params)
        flash[:success] = 'Profile Updated successfully!'
        redirect_to patients_dashboard_path
      else
        flash[:alert] = @patient.errors.full_messages.join(',')
        render :index
      end
    end

    private

    def set_patient
      @patient = current_patient
      redirect_to patients_dashboard_path if @patient.blank?
    end

    def patient_params
      params.require(:patient).permit(:name, :address, :gender, :phone)
    end
  end
end

app/views/patients/appointments/_form.html.haml
.col-md-12
  = form_for(@appointment, url: @appointment.new_record? ? patients_appointments_path : patients_appointment_path(@appointment.id)) do |f|
    .row
      .col
        %label Doctor
        = f.select :doctor_id , Doctor.all.collect {|d| [d.name, d.id]}, {prompt: 'Select Doctor'}, class: 'form-control'
      .col
        = f.label :date
        = f.date_field :date, class: 'form-control'
      .col
        = f.label :time
        = f.time_field :time, class: 'form-control'
    .row
      .col
        = f.label :description
        = f.text_area :description, class: 'form-control'
    %br
    .row
      .col
        = f.submit "Save", class: 'btn btn-primary'

app/views/patients/appointments/edit.html.haml
.container-fluid
  .row
    %h2 Edit Appointment
  .row
    = render 'form', locals: {appointment: @appointment}

app/views/patients/appointments/index.html.haml
.row
  .col-lg-12.col-md-12
    .row
      .col
        %h2 Appointments
      .col
        = link_to "New Appointment", new_patients_appointment_path, class: 'btn btn-primary float-right'
    .row
      .col
        %table.table.table-striped.table-sm
          - if @appointments.present?
            %thead
              %tr
                %th Doctore
                %th Date
                %th Time
                %th Status
                %th Action
            %tbody
              - @appointments.each do |appointment|
                %tr
                  %td
                    = appointment.doctor.try(:name)
                  %td
                    = appointment.date
                  %td
                    = appointment.time.strftime("%H:%M")
                  %td
                    = appointment.status
                  %td
                    = link_to "View", patients_appointment_path(appointment.id)
                    - if appointment.status == 'Request'
                      = link_to "Edit", edit_patients_appointment_path(appointment.id)
                      = link_to "Delete", patients_appointment_path(appointment.id), method: :delete
          - else
            %tr
              %td{style: 'text-align: center'}
                No Appointments!
        - if @appointments.present?
          %span.justify-content-left.float-left
          = page_entries_info @appointments, entry_name: 'appointments'
          %nav.d-inline-block.float-right{"aria-label" => "page navigation"}
            = paginate @appointments

app/views/patients/appointments/new.html.haml
.container-fluid
  .row
    %h2 New Appointment
  .row
    = render 'form', locals: {appointment: @appointment}

app/views/patients/appointments/show.html.haml
.row
  .col-lg-12.col-md-12
    .row
      .col
        %h2 Appointment
      .col
        = link_to "Back", patients_appointments_path, class: 'btn btn-primary float-right'
    .row
      .col
        %span Doctor:
        = @appointment.doctor.try(:name)
        %br
        %span Date:
        = @appointment.date
        %br
        %span Time:
        = @appointment.time.strftime("%H:%M")
        %br
        %span Status:
        = @appointment.status